import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const app=express();
const dir=path.dirname(fileURLToPath(import.meta.url));
app.use(express.json({limit:'1mb'}));
app.use(express.static(path.join(dir,'public')));
app.get('/health',(_req,res)=>res.json({ok:true,app:'AI News & Summary Video Studio',version:'1.1.0',openrouter_configured:Boolean(process.env.OPENROUTER_API_KEY)}));
function buildDemoStoryboard(text){const clean=text.replace(/\s+/g,' ').trim();const excerpt=clean.split(' ').filter(Boolean).slice(0,24).join(' ');return {mode:'demo',title:excerpt?excerpt.slice(0,80):'Ringkasan berita',total_duration_sec:60,scenes:[{scene:1,duration_sec:6,narration:excerpt||'Masukkan bahan berita untuk membuat storyboard.',on_screen_text:'PEMBUKA',visual_description:'Visual pembuka berita yang relevan',visual_prompt:'news opening, Indonesian news style'},{scene:2,duration_sec:8,narration:'Poin utama berita diringkas secara singkat dan jelas.',on_screen_text:'POIN UTAMA',visual_description:'Visual utama sesuai isi berita',visual_prompt:'relevant news visual, realistic'},{scene:3,duration_sec:8,narration:'Konteks penting dari informasi yang diberikan.',on_screen_text:'KONTEKS',visual_description:'Visual pendukung konteks',visual_prompt:'contextual news visual'},{scene:4,duration_sec:8,narration:'Detail penting berikutnya dari bahan sumber.',on_screen_text:'DETAIL',visual_description:'Visual detail berita',visual_prompt:'detailed news visual'},{scene:5,duration_sec:8,narration:'Dampak atau perkembangan yang disebutkan dalam sumber.',on_screen_text:'PERKEMBANGAN',visual_description:'Visual perkembangan',visual_prompt:'current event visual'},{scene:6,duration_sec:8,narration:'Informasi tambahan yang relevan dari sumber.',on_screen_text:'INFORMASI',visual_description:'Visual pendukung',visual_prompt:'supporting news visual'},{scene:7,duration_sec:6,narration:'Kesimpulan singkat berdasarkan bahan yang diberikan.',on_screen_text:'KESIMPULAN',visual_description:'Visual penutup informasi',visual_prompt:'news conclusion visual'},{scene:8,duration_sec:8,narration:'Itulah ringkasan berita kali ini.',on_screen_text:'SELESAI',visual_description:'Visual outro sederhana',visual_prompt:'clean news outro'}],closing:'Ikuti untuk ringkasan berita berikutnya.',hashtags:['#berita','#ringkasan','#informasi']};}
app.post('/api/storyboard',async(req,res)=>{const text=typeof req.body?.text==='string'?req.body.text.trim():'';if(!text)return res.status(400).json({error:'Teks berita wajib diisi.'});if(!process.env.OPENROUTER_API_KEY)return res.json({...buildDemoStoryboard(text),message:'OpenRouter API key belum dipasang. Struktur storyboard siap diuji.'});return res.status(501).json({error:'OpenRouter key terdeteksi, tetapi engine AI belum diaktifkan pada build ini.'});});
const port=process.env.PORT||3000;app.listen(port,()=>console.log('News Studio listening on '+port));
